# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.cov.outputs.coverage }}
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');
            fs.readdirSync('./').forEach(file => {
              console.log(file);
            });
            const content = fs.readFileSync('Readme.md', 'utf8');
            const lines = content.split('\n');
            lines[1] = 'This is the new content for the second line hey hey hey';

            fs.writeFileSync('Readme.md', lines.join('\n'));

            const response = await github.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'Readme.md'
            });

            await github.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'Readme.md',
                message: 'Update README',
                content: Buffer.from(lines.join('\n')).toString('base64'),
                sha: response.data.sha
              });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
