# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  workflow_call:

jobs:
  
  build:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.cov.outputs.coverage }}
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run fmt:check
    - run: npm run test:ci > test-log.txt
    - run: cat test-log.txt | grep -oE '^│\s*total\s+\│\s*([0-9.]+)%' text.txt | grep -oE '[0-9]+(\.[0-9]+)?%' | cut -d'.' -f1 > coverage.txt
    - run: |
        value=$(cat coverage.txt)
        echo "value=$value"
        export COV=$value
        npm i -g badgen-cli
        COLOR=$(node -p '+process.env.COV >= 70 ? `green` : `orange`')
        echo "color=$COLOR"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update README
      uses: actions/github-script@v3
      with:
        script: |
          const fs = require('fs');
          const content = fs.readFileSync('README.md', 'utf8');
          const lines = content.split('\n');
          lines[1] = 'This is the new content for the second line';

          fs.writeFileSync('README.md', lines.join('\n'));

          github.repos.createOrUpdateFileContents({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: 'README.md',
            message: 'Update README',
            content: Buffer.from(lines.join('\n')).toString('base64'),
            sha: context.payload.repository.head_commit.sha,
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




  # badge:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - run: echo steps.cov.outputs.coverage



  #       mkdir -p badges
  #       badgen -j coverage -s $COV% -c $COLOR > badges/coverage.svg
  #       const fs = require('fs');
  #       const content = fs.readFileSync('README.md', 'utf8');
  #       const lines = content.split('\n');
  #       lines[1] = 'This is the new content for the second line';

  #       fs.writeFileSync('README.md', lines.join('\n'));

  #       github.repos.createOrUpdateFileContents({
  #         owner: context.repo.owner,
  #         repo: context.repo.repo,
  #         path: 'README.md',
  #         message: 'Update README',
  #         content: Buffer.from(lines.join('\n')).toString('base64'),
  #         sha: context.payload.repository.head_commit.sha,
  #       });